add startArgs options. to use NAME:    start - start tunnels by name from the configuration file
USAGE:
   ngrok start [command options] [arguments...]

DESCRIPTION:
   Starts tunnels by name from the configuration file. You may specify any
   number of tunnel names. You may start all tunnels in the configuration
   file with the --all switch.

EXAMPLES:
   ngrok start dev        # start tunnel named 'dev' in the configuration file
   ngrok start web blog   # start tunnels named 'web' and 'blog'
   ngrok start --all      # start all tunnels defined in the config file

OPTIONS:
   --all		start all tunnels in the configuration file
   --authtoken 		ngrok.com authtoken identifying a user
   --config		path to config files; they are merged if multiple
   --log "false"	path to log file, 'stdout', 'stderr' or 'false'
   --log-format "term"	log record format: 'term', 'logfmt', 'json'
   --log-level "info"	logging level
   --none		start running no tunnels
   --region 		ngrok server region [us, eu, au, ap] (default: us)

ERROR:  Your configuration file must define at least one tunnel when using --all. To intentionally start no tunnels, use `ngrok start --none.`